runtime: nodejs12

instance_class: F2




handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto

# automatic_scaling:
  # min_num_instances: 2
  # max_num_instances: 8
  # max_concurrent_requests: 10
  # target_cpu_utilization: 0.85
  # min_pending_latency: 100ms
  # max_pending_latency: 250ms

  


  